#
image: node:8.9.4

cache:
    paths:
        - node_modules/

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - npm install hexo-cli -g
    - npm install

pages:
    script:
        - hexo generate
    artifacts:
        paths:
            - public
    only:
        - master