image: node:8.9.4
pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-generator-feed --save
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master